services:
  - type: web
    name: vixsrc-render
    runtime: node
    buildCommand: bash install-tor.sh && npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
